package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"
	"time"

	"github.com/Plebysnacc/kummerkasten/graph/model"
)

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, user model.NewUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: AddUser - addUser"))
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: Ticket - ticket"))
}

// Label is the resolver for the label field.
func (r *queryResolver) Label(ctx context.Context, name string) (*model.Label, error) {
	panic(fmt.Errorf("not implemented: Label - label"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	dummyUser := &model.User{
		ID:           "1",
		Mail:         "dummy@kummerkasten.local",
		Firstname:    "dummy",
		Lastname:     "local",
		Role:         "dummy",
		CreatedAt:    time.Now(),
		LastModified: time.Now(),
	}
	return dummyUser, nil
}

// Setting is the resolver for the setting field.
func (r *queryResolver) Setting(ctx context.Context, key string) (*model.Setting, error) {
	panic(fmt.Errorf("not implemented: Setting - setting"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
