package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"
	"log"
	"strconv"
	"time"

	"github.com/Plebysnacc/kummerkasten/graph/model"
)

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, user model.NewUser) (*model.User, error) {
	newUser := &model.User{
		Mail:         user.Mail,
		Firstname:    user.Firstname,
		Lastname:     user.Lastname,
		Role:         "user",
		CreatedAt:    time.Now(),
		LastModified: time.Now(),
	}

	_, dbErr := r.DB.NewInsert().Model(newUser).Returning("id").Exec(ctx)
	if dbErr != nil {
		log.Printf("Failed to add user: %v", dbErr)
		return nil, dbErr
	}

	return newUser, nil
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: Ticket - ticket"))
}

// Label is the resolver for the label field.
func (r *queryResolver) Label(ctx context.Context, name string) (*model.Label, error) {
	panic(fmt.Errorf("not implemented: Label - label"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	var user model.User

	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID format: %v", err)
	}

	err = r.DB.NewSelect().Model(&user).Where("id = ?", userID).Scan(ctx)
	if err != nil {
		log.Printf("failed to fetch user with ID %d: %v", userID, err)
		return nil, err
	}

	return &user, nil
}

// Setting is the resolver for the setting field.
func (r *queryResolver) Setting(ctx context.Context, key string) (*model.Setting, error) {
	panic(fmt.Errorf("not implemented: Setting - setting"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var users []*model.User

	err := r.DB.NewSelect().Model(&users).Scan(ctx)
	if err != nil {
		log.Printf("failed to fetch Users: %v", err)
		return nil, err
	}

	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
